version: '3'
services:
  irrigaapp:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATA_MONGODB_URI=${MONGODB_URI}
      - SPRING_DATA_MONGODB_DATABASE=${MONGODB_DATABASE}
      - PROFILE=${PROFILE}
