version: '3'
services:
  mongo:
    image: mongo:4.4
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: irrigaappbd
    volumes:
      - ./data/db:/data/db

  irrigaapp:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://admin:password@mongo:27017/irrigaappbd?authSource=admin
      - PROFILE=prd
