name: Continuous Delivery

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      MONGO_URI: ${{ secrets.MONGO_URI }}

    steps:
      - name: Git Checkout
        uses: actions/checkout@v4

      - name: Setup Java SDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Verify MongoDB URI
        run: echo "MONGO_URI is set to $MONGO_URI"

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: denisecmf
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: denisecmf/irrigaapp:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    env:
      MONGO_URI: ${{ secrets.MONGO_URI }} # Definindo a variável no job deploy

    steps:
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: irriga-app-api-dev
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          images: 'denisecmf/irrigaapp:latest'
