#deploy para o ambiente de desenvolvimento e testes sempre que resultar em um pull_request para a developer

name: Build and deploy container app to Azure Web App - irriga-app-api-dev

on:
  pull_request:
    branches:
      - developer
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: denisecmf/irrigaapp:latest
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'irriga-app-api-dev'
        slot-name: 'development'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_237caaae07294c338495f1396e62eb85 }}
        images: denisecmf/irrigaapp:latest
